const { exec } = require("child_process");
const { promisify } = require("util");
const execAsync = promisify(exec);

/**
 * GitCommitter - Automatically commits task completions to git
 *
 * Implements the MAKER requirement for versioning after each task.
 */
class GitCommitter {
  /**
   * @param {string} projectRoot - Root directory of the git repository
   */
  constructor(projectRoot) {
    this.projectRoot = projectRoot;
  }

  /**
   * Commit a completed task's changes
   * @param {Object} task - The completed task
   * @param {Array} results - Step results
   * @returns {Promise<Object>} - Commit result
   */
  async commitTaskCompletion(task, results) {
    // Only commit if task completed successfully
    if (task.status !== "completed") {
      return { committed: false, reason: "task-not-completed", status: task.status };
    }

    try {
      // 1. Check if git is initialized
      try {
        await execAsync("git rev-parse --git-dir", { cwd: this.projectRoot });
      } catch (err) {
        // Git not initialized - silently skip
        return { committed: false, reason: "no-git-repo" };
      }

      // 2. Stage workspace files (if workspace exists)
      if (task.workspacePath) {
        try {
          await execAsync(`git add "${task.workspacePath}"`, { cwd: this.projectRoot });
        } catch (err) {
          // Workspace might not have changes
          console.warn(`[GitCommitter] Failed to stage workspace: ${err.message}`);
        }
      }

      // 3. Check if there are actually changes to commit
      const { stdout: status } = await execAsync("git status --porcelain", {
        cwd: this.projectRoot,
      });

      if (!status.trim()) {
        return { committed: false, reason: "no-changes" };
      }

      // 4. Build commit message
      const commitMsg = this.buildCommitMessage(task, results);

      // 5. Create commit
      const { stdout } = await execAsync(
        `git commit -m "${this.escapeCommitMessage(commitMsg)}"`,
        { cwd: this.projectRoot }
      );

      return {
        committed: true,
        message: commitMsg,
        output: stdout,
        changedFiles: status.split("\n").filter(Boolean).length,
      };
    } catch (err) {
      console.error("[GitCommitter] Error during commit:", err.message);
      return {
        committed: false,
        error: err.message,
      };
    }
  }

  /**
   * Build a descriptive commit message
   * @param {Object} task
   * @param {Array} results
   * @returns {string}
   */
  buildCommitMessage(task, results) {
    const stepCount = results?.length || task.steps?.length || 0;
    const winnerCount = results?.filter((r) => r.result?.winner).length || 0;

    const lines = [
      `Task: ${task.title}`,
      "",
      `Id: ${task.id}`,
      `Steps: ${stepCount}${task.steps ? `/${task.steps.length}` : ""}`,
      `Winners: ${winnerCount}`,
      `Model: ${task.model}`,
    ];

    if (task.voteModel && task.voteModel !== task.model) {
      lines.push(`Vote Model: ${task.voteModel}`);
    }

    lines.push("");
    lines.push("🤖 Auto-generated by Ultracode MAKER");

    return lines.join("\n");
  }

  /**
   * Escape commit message for shell
   * @param {string} msg
   * @returns {string}
   */
  escapeCommitMessage(msg) {
    return msg.replace(/"/g, '\\"').replace(/\$/g, "\\$").replace(/`/g, "\\`");
  }

  /**
   * Initialize git repository if it doesn't exist
   * @returns {Promise<Object>}
   */
  async initRepo() {
    try {
      await execAsync("git init", { cwd: this.projectRoot });
      await execAsync('git config user.name "Ultracode MAKER"', {
        cwd: this.projectRoot,
      });
      await execAsync('git config user.email "maker@ultracode.local"', {
        cwd: this.projectRoot,
      });
      return { initialized: true };
    } catch (err) {
      return { initialized: false, error: err.message };
    }
  }

  /**
   * Get recent commits
   * @param {number} count - Number of commits to fetch
   * @returns {Promise<Array>}
   */
  async getRecentCommits(count = 10) {
    try {
      const { stdout } = await execAsync(
        `git log -${count} --pretty=format:"%H|%an|%ae|%at|%s"`,
        { cwd: this.projectRoot }
      );

      return stdout
        .split("\n")
        .filter(Boolean)
        .map((line) => {
          const [hash, author, email, timestamp, subject] = line.split("|");
          return {
            hash,
            author,
            email,
            timestamp: parseInt(timestamp),
            subject,
          };
        });
    } catch (err) {
      return [];
    }
  }
}

module.exports = { GitCommitter };
